collections:
  case_studies:
    output: true

defaults:
  - scope:
      path: ""
      type: "case_studies"
    values:
      layout: "case_study"
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag